# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gYzMu1jPz5rQGSZ-3hTedzQkdiS616RP
"""

def reverse_string(s):
  """Reverses the given string."""
  return s[::-1]

print(reverse_string("Hello, World!")